=== jmoreno-git/23-dam-m06/12/dom/materials/SchoolDomAp/resources/school.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="school" type="t_school" />
    
    <xs:complexType name="t_school">
        <xs:sequence>
            <xs:element name="name" type="xs:token"/>
            <xs:element name="groups" type="t_groups"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="t_groups">
        <xs:sequence>
            <xs:element name="group" type="t_group" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>    
    
    <xs:complexType name="t_group">
        <xs:sequence>
            <xs:element name="name" type="xs:token"/>
            <xs:element name="tutor" type="xs:token"/>
            <xs:element name="curriculum" type="xs:token"/>
            <xs:element name="students" type="t_students"/>
        </xs:sequence>
    </xs:complexType>    
    
    <xs:complexType name="t_students">
        <xs:sequence>
            <xs:element name="student" type="t_student" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>     
    
    <xs:complexType name="t_student">
        <xs:sequence>
            <xs:element name="name" type="t_name"/>
            <xs:element name="surname" type="xs:token"/>
            <xs:element name="emails" type="t_emails"/>
            <xs:element name="age" type="xs:positiveInteger"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
    
    <xs:complexType name="t_emails">
        <xs:sequence>
            <xs:element name="email" type="t_email" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>   
    
    <xs:simpleType name="t_email">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9]{1,15}@[a-zA-Z0-9]{1,25}[.][a-z]{2,4}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="t_name">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z ]{1,30}"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== jmoreno-git/23-dam-m06/12/dom/SchoolDomAp/SchoolDomAp/resources/school.xml
<?xml version="1.0" encoding="UTF-8"?>
<school xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="school.xsd">
  <name>Institut Provençana</name>
  <groups>
    <group>
      <name>DAM2</name>
      <tutor>Daniel</tutor>
      <curriculum>Desenvolupament aplicacions multiplataforma</curriculum>
      <students>
        <student id="s001">
          <name>Maria Lluisa</name>
          <surname>Pérez Lluch</surname>
          <emails>
            <email>email001@hotmail.com</email>
          </emails>
          <age>11</age>
        </student>
        <student id="s002">
          <name>Joan Anton</name>
          <surname>Martínez Ruiz</surname>
          <emails>
            <email>email002@hotmail.com</email>
            <email>email2002@hotmail.com</email>
          </emails>
          <age>12</age>
        </student>
      </students>
    </group>
    <group>
      <name>DAW2</name>
      <tutor>Isabel</tutor>
      <curriculum>Desenvolupament aplicacions web</curriculum>
      <students>
          <student id="s003">
          <name>Maria</name>
          <surname>Ruiz Ruiz</surname>
          <emails>
          </emails>
          <age>13</age>
        </student>
      </students>
    </group>   
    <group>
      <name>SMX1A</name>
      <tutor>Joan Salvador</tutor>
      <curriculum>Sistemes microinformàtics i xarxes</curriculum>
      <students>
      </students>
    </group>  
  </groups>
</school>
