=== jmoreno-git/23-dam-m06/31/dam2-m06-uf3-SchoolAppWithExistDb_Alcala_Ivan/dam2-m06-uf3-SchoolAppWithExistDb/resources/school.xsd
<?xml version="1.0"?>

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <xs:element name="school" type="typeSchool"/>
    
    <xs:complexType name="typeSchool">
        <xs:sequence>
            <xs:element name="groups" type="typeGroups"/>
          </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="typeGroups">
        <xs:sequence>
            <xs:element name="group" type="typeGroup" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="typeStudents">
        <xs:sequence>
            <xs:element name="student" type="typeStudent" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="typeGroup" mixed="true">
        <xs:sequence>
            <xs:element name="groupname" type="xs:string"/>
            <xs:element name="duration" type="xs:positiveInteger"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="enrolled" type="typeStudents"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>    
    
    <xs:complexType name="typeStudent" mixed="true">
        <xs:sequence>
            <xs:element name="studentname" type="xs:string"/>
            <xs:element name="age" type="xs:positiveInteger"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
       
</xs:schema>

=== jmoreno-git/23-dam-m06/31/dam2-m06-uf3-SchoolAppWithExistDb/dam2-m06-uf3-SchoolAppWithExistDb/resources/school.xml
<?xml version="1.0" encoding="UTF-8"?>
<school
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='school.xsd'>
    <groups>
        <group id="g01">
            <groupname>DAW</groupname>
            <duration>2000</duration>
            <description>Desenvolupament d'aplicacions web</description>
            <enrolled>
                <student id="alu1">
                    <studentname>Name1</studentname>
                    <age>21</age>
                </student>
                <student id="alu2">
                    <studentname>Name2</studentname>
                    <age>22</age>
                </student>
                <student id="alu3">
                    <studentname>Name3</studentname>
                    <age>23</age>
                </student>
            </enrolled>
        </group>
        <group id="g02">
            <groupname>BIM</groupname>
            <duration>600</duration>
            <description>Modelatge de la informació de la cosntrucció</description>
            <enrolled>
            </enrolled>
        </group>
        <group id="g03">
            <groupname>DAM</groupname>
            <duration>2000</duration>
            <description>esenvolupament d'aplicacions multiplataforma</description>
            <enrolled>
                <student id="alu4">
                    <studentname>Name4</studentname>
                    <age>18</age>
                </student>
                <student id="alu5">
                    <studentname>Name5</studentname>
                    <age>19</age>
                </student>
                <student id="alu6">
                    <studentname>Name6</studentname>
                    <age>20</age>
                </student>
                <student id="alu7">
                    <studentname>Name7</studentname>
                    <age>21</age>
                </student>
            </enrolled>
        </group>
    </groups>

</school>
